### ISSUE TITLE
Use on 1.10

### ISSUE THREAD

**Issue by willtebbutt** [dfdx/Umlaut.jl#41]
At present, CompilerPluginTools.jl does not precompile on 1.10.0-beta2. I do not know this will cease to be the case.

For Julia version 1.9 and up, this package doesn't technically require CompilerPluginTools.jl.

@dfdx do you have thoughts on what the best way forwards is for having this package work on 1.10? The options that I can see are
1. fix CompilerPluginTools on 1.10 (I've not interacted with that package so don't know how to fix it, and I'm not whether it's actively maintained), or
1. drop Julia versions below 1.8, and this package's dependency on CompilerPluginTools.

What are your thoughts? Maybe I've missed an option?

**Comment by dfdx** [comment]
#43 explores option (2). As you can see in [CI/CD](https://github.com/dfdx/Umlaut.jl/actions/runs/5931096765/job/16082223789?pr=43#step:5:92), the tests still fail because of changes in `Core.Compiler.IRCode` structure. We can fix it now, but since it's not a release yet, there's a high chance to get more breaking changes very soon. So unless you have an urgent use case, I'd say let's wait for the release and see what it takes to make Umlaut work on Julia 1.10.

**Comment by willtebbutt** [comment]
Sounds good to me

**Comment by willtebbutt** [comment]
Fixed by #43
